<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EgressPool\EgressPool.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>Egress.DependencyInjection</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Description>Dependency injection and IHttpClientFactory integration for EgressPool.</Description>
    <PackageTags>egress;networking;dependency-injection;httpclientfactory</PackageTags>
  </PropertyGroup>

</Project>
