name: Commit

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  nuget:
    needs: tests
    uses: ./.github/workflows/nuget.yml
    secrets: inherit
