name: NuGet Workflow

on:
  workflow_call:
    secrets:
      NUGET_API_KEY:
        required: true
  workflow_dispatch:

permissions:
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6
        with:
          dotnet-version: latest

      - name: Pack
        run: |
          dotnet pack src/EgressPool.DependencyInjection/EgressPool.DependencyInjection.csproj --configuration Release --output artifacts --nologo
          dotnet pack src/EgressPool/EgressPool.csproj --configuration Release --output artifacts --nologo

      - name: Upload package artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: nuget-packages
          path: artifacts
          compression-level: 9
          if-no-files-found: error

      - name: NuGet Push
        run: |
          dotnet nuget push artifacts/EgressPool.[0-9]*.nupkg --source https://api.nuget.org/v3/index.json --api-key "$NUGET_API_KEY" --skip-duplicate
          dotnet nuget push artifacts/EgressPool.DependencyInjection.*.nupkg --source https://api.nuget.org/v3/index.json --api-key "$NUGET_API_KEY" --skip-duplicate
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
